title: RLA Review — Arlo
description: >-
  Independent review and transparency analysis of Risk-Limiting Audits
  conducted using Arlo (VotingWorks).
url: "https://nealmcb.github.io"
baseurl: "/rla-review-arlo"
theme: minima
permalink: pretty
plugins:
  - jekyll-feed
markdown: kramdown
